#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

# #######################################
REPO=vim-program
FILE=program.vim
LOCAL=""
while getopts "l" arg
do
	case $arg in
            l) LOCAL="yes" ;;
        esac
done
ANON=`date`
print $ANON
print "Local Deployment..."
cp plugin/$FILE $HOME/.vim/bundle/$REPO/plugin/$FILE


if [ "$LOCAL" == "" ] ; then
     IP=192.168.1.1
     fping -c1 -t300 $IP 2>/dev/null 1>/dev/null
     if [ $? -eq 0 ] ; then
          git add plugin/$FILE
          git add pushit
          git commit -m "Update"
          git push -u origin master
     fi
fi

