#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

# #######################################
REPO=vim-program
FILE=program.vim
LOCAL=""
while getopts "lgc" arg
do
	case $arg in
            l) LOCAL="yes" 
               ANON=`date`
               print $ANON
               print "Local Deployment..."
               cp plugin/$FILE $HOME/.vim/bundle/$REPO/plugin/$FILE
               ls -l $HOME/.vim/bundle/$REPO/plugin/$FILE
               exit 0
               ;;
            g) LOCAL="no" 
               git add plugin/$FILE
               git add README.md
               git add pushit
               git commit -m "Update"
               git push -u origin master
               print "Local Deployment..."
               cp plugin/$FILE $HOME/.vim/bundle/$REPO/plugin/$FILE
               ls -l $HOME/.vim/bundle/$REPO/plugin/$FILE
               exit 0
               ;;
            c) print "Clearing Local Deployment..."
               rm -rf $HOME/.vim/bundle/$REPO
               exit 0
               ;;
        esac
done


# if [ "$LOCAL" == "" ] ; then
# fi
